using UnityEngine;

// Chooses the player's sprite animation. All selection rules live here; the Animator only maps each
// PlayerAnimState to its clip (generated by PlayerSpriteGenerator), so adding a pose never means
// rewiring transitions by hand.
public partial class playerController2
{
    private static readonly int AnimStateId = Animator.StringToHash("state");
    private const float AnimMoveThreshold = 0.1f;

    [Header("Animation")]
    [Tooltip("How long the finger-snap pose plays after a banish fires (the Snap clips are 5 frames at 14 fps).")]
    [SerializeField, Min(0f)] private float snapPoseDuration = 5f / 14f;

    private float snapPoseTimer;
    private bool wallJumpPose;
    private bool wallJumpFacesRight;

    private enum ArmPose { None, Aim, Snap }

    private void UpdateAnimation()
    {
        snapPoseTimer = Mathf.Max(0f, snapPoseTimer - Time.deltaTime);
        bool facesRight = VisualFacingRight();
        spriteRenderer.flipX = !facesRight;
        // Reversed gravity stands the player on the ceiling, so draw them upside down.
        spriteRenderer.flipY = GravityUpSign < 0f;
        animator.SetInteger(AnimStateId, (int)ChooseAnimState(facesRight));
    }

    private bool VisualFacingRight()
    {
        if (wallJumpPose) return wallJumpFacesRight;                         // Kick away from the wall.
        if (grabbed != null) return grabbed.Body.position.x > rb.position.x; // Keep both hands on the box.
        return isFacingRight;
    }

    private PlayerAnimState ChooseAnimState(bool facesRight)
    {
        var arms = snapPoseTimer > 0f ? ArmPose.Snap : isTargeting ? ArmPose.Aim : ArmPose.None;
        float upSpeed = rb.linearVelocity.y * GravityUpSign;
        float forwardSpeed = rb.linearVelocity.x * (facesRight ? 1f : -1f);
        bool walking = Mathf.Abs(forwardSpeed) > AnimMoveThreshold;

        if (isSliding && upSpeed <= AnimMoveThreshold)
            return arms switch
            {
                ArmPose.Snap => PlayerAnimState.SnapSlide,
                ArmPose.Aim => PlayerAnimState.AimSlide,
                _ => PlayerAnimState.WallSlide,
            };

        if (!touchingDirection.isGrounded)
        {
            if (arms == ArmPose.Snap) return PlayerAnimState.SnapAir;
            if (arms == ArmPose.Aim) return PlayerAnimState.AimAir;
            if (grabbed != null) return PlayerAnimState.GrabAir;
            if (wallJumpPose) return PlayerAnimState.WallJump;
            return upSpeed > 0f ? PlayerAnimState.Rise : PlayerAnimState.Fall;
        }

        if (arms == ArmPose.Snap) return walking ? PlayerAnimState.SnapWalk : PlayerAnimState.SnapIdle;
        if (arms == ArmPose.Aim) return walking ? PlayerAnimState.AimWalk : PlayerAnimState.AimIdle;
        if (grabbed != null)
            return !walking ? PlayerAnimState.GrabIdle
                : forwardSpeed > 0f ? PlayerAnimState.GrabPush : PlayerAnimState.GrabPull;
        return walking ? PlayerAnimState.Walk : PlayerAnimState.Idle;
    }
}
